export const FETCH_QUZES_START = 'FETCH_QUZES_START'
export const FETCH_QUZES_SUCCESS = 'FETCH_QUZES_SUCCESS'
export const FETCH_QUZES_ERROR = 'FETCH_QUZES_ERROR'
export const FETCH_QUIZ_SUCCESS = 'FETCH_QUIZ_SUCCESS'